// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    var data, ip, parseIP;
    ip = '192.168.1.50';
    parseIP = function(ip) {
      var parts;
      return parts = ip.split('.').map(function(i) {
        return parseInt(i);
      });
    };
    data = parseIP(ip);
    return console.log(data);
  });

}).call(this);
